# generated by mBlock5 for CyberPi
import event, time, cyberpi, mbot2

# Inicialización requerida
cyberpi.driver.cloud_translate.TTS_URL = "{TTSURL}"
cyberpi.driver.cloud_translate.set_token("{ACCESSTOKEN}")
cyberpi.speech.set_recognition_address(url="{NAVIGATEURL}")
cyberpi.speech.set_access_token(token="{ACCESSTOKEN}")

# ─────────────────────────────────────────
# PROCESADOR DE COMANDOS EN ESPAÑOL
# ─────────────────────────────────────────
def procesar_español(texto):
    texto = texto.lower()
    cyberpi.console.println("ES: " + texto)

    if "adelante" in texto or "avanza" in texto:
        cyberpi.cloud.tts("es", "Avanzando")
        mbot2.forward(50, 2)

    elif "atras" in texto or "retrocede" in texto:
        cyberpi.cloud.tts("es", "Retrocediendo")
        mbot2.backward(50, 2)

    elif "para" in texto or "detente" in texto:
        cyberpi.cloud.tts("es", "Detenido")
        mbot2.stop()

    elif "izquierda" in texto:
        cyberpi.cloud.tts("es", "Girando a la izquierda")
        mbot2.turn_left(50, 1)

    elif "derecha" in texto:
        cyberpi.cloud.tts("es", "Girando a la derecha")
        mbot2.turn_right(50, 1)

    elif "enciende" in texto or "luz" in texto:
        cyberpi.cloud.tts("es", "Luz encendida")
        cyberpi.led.on(255, 255, 255)

    elif "apaga" in texto:
        cyberpi.cloud.tts("es", "Luz apagada")
        cyberpi.led.off()

    elif "ingles" in texto or "english" in texto:
        cyberpi.cloud.tts("es", "Cambiando a inglés")
        return "en"

    else:
        cyberpi.cloud.tts("es", "No entendí el comando")

    return "es"

# ─────────────────────────────────────────
# PROCESADOR DE COMANDOS EN INGLÉS
# ─────────────────────────────────────────
def procesar_ingles(texto):
    texto = texto.lower()
    cyberpi.console.println("EN: " + texto)

    if "forward" in texto or "go" in texto:
        cyberpi.cloud.tts("en", "Moving forward")
        mbot2.forward(50, 2)

    elif "backward" in texto or "back" in texto:
        cyberpi.cloud.tts("en", "Moving backward")
        mbot2.backward(50, 2)

    elif "stop" in texto:
        cyberpi.cloud.tts("en", "Stopped")
        mbot2.stop()

    elif "left" in texto:
        cyberpi.cloud.tts("en", "Turning left")
        mbot2.turn_left(50, 1)

    elif "right" in texto:
        cyberpi.cloud.tts("en", "Turning right")
        mbot2.turn_right(50, 1)

    elif "light on" in texto:
        cyberpi.cloud.tts("en", "Light on")
        cyberpi.led.on(255, 255, 255)

    elif "light off" in texto:
        cyberpi.cloud.tts("en", "Light off")
        cyberpi.led.off()

    elif "spanish" in texto or "espanol" in texto:
        cyberpi.cloud.tts("en", "Switching to Spanish")
        return "es"

    else:
        cyberpi.cloud.tts("en", "Command not recognized")

    return "en"

# ─────────────────────────────────────────
# PROGRAMA PRINCIPAL
# ─────────────────────────────────────────
@event.start
def on_start():
    idioma = "es"  # idioma inicial: "es" o "en"

    # Conectar WiFi
    cyberpi.console.println("Conectando WiFi...")
    cyberpi.wifi.connect('#WUAMC', 'wificua6')
    time.sleep(3)

    if cyberpi.wifi.is_connect():
        cyberpi.console.println("WiFi OK!")
        cyberpi.led.on(0, 255, 0)
        cyberpi.cloud.tts("es", "Listo, escuchando")
    else:
        cyberpi.console.println("Sin WiFi")
        cyberpi.led.on(255, 0, 0)

    time.sleep(2)

    # Bucle principal de escucha
    while True:
        cyberpi.console.println("Idioma: " + idioma)

        if idioma == "es":
            cyberpi.cloud.listen('spanish', 4)
        else:
            cyberpi.cloud.listen('english', 4)

        time.sleep(4.5)

        resultado = cyberpi.cloud.listen_result()

        if resultado and resultado != "":
            if idioma == "es":
                idioma = procesar_español(resultado)
            else:
                idioma = procesar_ingles(resultado)
        else:
            cyberpi.console.println("Sin resultado...")

        time.sleep(0.5)